### ISSUE TITLE
Build error on arm platform

### ISSUE THREAD

**Issue by JackBoosY** [awslabs/aws-checksums#17]
Hi Developer,
I tried to build aws-checksums on the **arm** platform using vcpkg, but I encountered the following errors:
```
...
F:\vcpkg\buildtrees\aws-checksums\src\v0.1.2-ba00ff7d02\source\visualc\visualc_crc32c_sse42.c(54): warning C4013: '_mm_crc32_u8' undefined; assuming extern returning int
F:\vcpkg\buildtrees\aws-checksums\src\v0.1.2-ba00ff7d02\source\visualc\visualc_crc32c_sse42.c(68): warning C4013: '_mm_crc32_u32' undefined; assuming extern returning int
...
visualc_crc32c_sse42.c.obj : error LNK2019: unresolved external symbol _mm_crc32_u8 referenced in function aws_checksums_crc32c_hw
visualc_crc32c_sse42.c.obj : error LNK2019: unresolved external symbol _mm_crc32_u32 referenced in function aws_checksums_crc32c_hw
aws-checksums.dll : fatal error LNK1120: 2 unresolved externals
```

When I delved into the source code, I found that the function __mm_crc32_u8_ / __mm_crc32_u32_ / __mm_crc32_u64_ was called on the **arm** platform. By looking at the [MSDN documentation](https://docs.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list?view=vs-2017), I found that these functions only support the **x86** / **x64** platform.
I also noticed that the source has arm code files, but there is no macro distinction in _CMakeLists.txt_, which indicates that x86 / x64 code files will **also** be compiled on all platforms.
Is it right?

Related: [#4910](https://github.com/microsoft/vcpkg/issues/4910).

**Comment by ColdenCullen** [comment]
You're correct, that file should be ignored when the architecture is arm. It looks like we just assumed visualc implies x86|x64, which is clearly not the case. This should be pretty easy to fix, we'll let you know when it's in.

**Comment by ColdenCullen** [comment]
@JackBoosY can you pull and test #18 for me please?

**Comment by JackBoosY** [comment]
@ColdenCullen  Still have problem by using your workaround:
```
     4>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification [F:\vcpkg\buildtrees\aws-checksums\arm-uwp-dbg\aws-checksums.vcxproj]
            Creating library F:/vcpkg/buildtrees/aws-checksums/arm-uwp-dbg/Debug/aws-checksums.lib and object F:/vcpkg/buildtrees/aws-checksums/arm-uwp-dbg/Debug/aws-checksums.exp
     4>crc.obj : error LNK2019: unresolved external symbol aws_checksums_crc32c_hw referenced in function aws_checksums_crc32c [F:\vcpkg\buildtrees\aws-checksums\arm-uwp-dbg\aws-checksums.vcxproj]
     4>F:\vcpkg\buildtrees\aws-checksums\arm-uwp-dbg\Debug\aws-checksums.dll : fatal error LNK1120: 1 unresolved externals [F:\vcpkg\buildtrees\aws-checksums\arm-uwp-dbg\aws-checksums.vcxproj]
```

**Comment by ColdenCullen** [comment]
I see the problem, there was no CRC implementation on ARM at all. I just added one that forwards to the software CRC'er, once the CI passes I'll ask you to test it again.

**Comment by JonathanHenson** [comment]
IIRC msft finally published the armv8 intrensics, so the hardware version can be implemented if needed.

**Comment by ColdenCullen** [comment]
@JackBoosY try now?
@JonathanHenson that would be pretty cool, we should probably schedule time to do that.

**Comment by JackBoosY** [comment]
@ColdenCullen Works! Thanks! I will generate a patch for the current version and update this port in the future.

**Comment by ColdenCullen** [comment]
Closing as the PR was merged.
