### ISSUE TITLE
aws/common/cpuid.h: No such file or directory

### ISSUE THREAD

**Issue by disa6302** [awslabs/aws-checksums#35]
I get this error when I run `make` on aws-checksums on an Ubuntu 18.04 x-86 EC2 instance. This is my CMake command:

`cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/home/ubuntu/aws-libs`

Is there something I am doing wrong? Has anybody faced this issue before?

**Comment by rccarper** [comment]
Hello, did you build [aws-c-common](https://github.com/awslabs/aws-c-common) first?  It sounds like that dependency may be missing.
