### ISSUE TITLE
gcc-8 build failed

### ISSUE THREAD

**Issue by egorpugin** [awslabs/aws-checksums#8]
Hi, I'm trying to build aws-sdk-cpp 1.7.1 which requires this lib.
And building this lib I see the error on gcc-8, ubuntu 18.04.

```
"/usr/bin/gcc-8" "-c" "/home/egor/.sw/storage/pkg/08/96/8a/68/1247/src/sdir/source/intel/crc32c_sse42_asm.c" "-I/home/egor/.sw/storage/pkg/08/96/8a/68/1247/src/sdir/include" 
/home/egor/.sw/storage/pkg/08/96/8a/68/1247/src/sdir/source/intel/crc32c_sse42_asm.c: In function ‘s_crc32c_sse42_clmul_256’:
/home/egor/.sw/storage/pkg/08/96/8a/68/1247/src/sdir/source/intel/crc32c_sse42_asm.c:61:5: error: ‘asm’ operand has impossible constraints
     asm volatile("enter_256_%=:"
     ^~~
```

I use custom build and not sure completely whether it is my mistake or library issue.

**Comment by egorpugin** [comment]
Changing `+c` and `+d` in `asm` blocks to `+g` helps.

**Comment by egorpugin** [comment]
Yes, I used release build.
Sent a PR - #9

**Comment by JonathanHenson** [comment]
hmmmmm..... I just did a gcc-8 release build and got the following:
19:54:56
[Container] 2018/11/19 19:54:56 Running command ./codebuild/common-linux.sh -DCMAKE_BUILD_TYPE="RelWithDebInfo"

19:54:58
-- The C compiler identification is GNU 8.1.0

19:54:58
-- Check for working C compiler: /usr/bin/gcc-8

19:54:58
-- Check for working C compiler: /usr/bin/gcc-8 -- works

19:54:58
-- Detecting C compiler ABI info

19:54:58
-- Detecting C compiler ABI info - done

19:54:58
-- Detecting C compile features

19:54:58
-- Detecting C compile features - done

19:54:58
-- Configuring done

19:54:58
-- Generating done

19:54:58
-- Build files have been written to: /codebuild/output/src122671398/src/github.com/awslabs/aws-checksums/build

19:54:58
Scanning dependencies of target aws-checksums

19:54:58
[ 9%] Building C object CMakeFiles/aws-checksums.dir/source/crc_jni.c.o

19:54:58
[ 18%] Building C object CMakeFiles/aws-checksums.dir/source/crc_sw.c.o

19:54:58
[ 27%] Building C object CMakeFiles/aws-checksums.dir/source/cpuid_generic.c.o

19:54:58
[ 36%] Building C object CMakeFiles/aws-checksums.dir/source/crc.c.o

19:54:58
[ 45%] Building C object CMakeFiles/aws-checksums.dir/source/intel/cpuid.c.o

19:54:58
[ 54%] Building C object CMakeFiles/aws-checksums.dir/source/intel/crc32c_sse42_asm.c.o

19:54:58
[ 63%] Building C object CMakeFiles/aws-checksums.dir/source/arm/cpuid_arm.c.o

19:54:58
[ 72%] Linking C static library libaws-checksums.a

19:54:58
[ 72%] Built target aws-checksums

19:54:58
Scanning dependencies of target aws-checksums-tests

19:54:58
[ 81%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/crc_test.c.o

19:54:58
[ 90%] Building C object CMakeFiles/aws-checksums-tests.dir/tests/run_tests.c.o

19:54:58
[100%] Linking C executable aws-checksums-tests

19:54:58
[100%] Built target aws-checksums-tests

19:54:58
Running tests...

19:54:58
Test project /codebuild/output/src122671398/src/github.com/awslabs/aws-checksums/build

19:54:58
Start 1: crc32c

19:54:58
1/2 Test #1: crc32c ........................... Passed 0.00 sec

19:54:58
Start 2: crc32

19:54:58
2/2 Test #2: crc32 ............................ Passed 0.00 sec

19:54:58

19:54:58
100% tests passed, 0 tests failed out of 2

19:54:58

19:54:58
Total Test time (real) = 0.00 sec

19:54:58
[ 72%] Built target aws-checksums

19:54:58
[100%] Built target aws-checksums-tests

19:54:58
Install the project...

19:54:58
-- Install configuration: "RelWithDebInfo"

19:54:58
-- Installing: /codebuild/output/src122671398/src/github.com/awslabs/install/include/aws/checksums/crc_jni.h

19:54:58
-- Installing: /codebuild/output/src122671398/src/github.com/awslabs/install/include/aws/checksums/crc.h

19:54:58
-- Installing: /codebuild/output/src122671398/src/github.com/awslabs/install/include/aws/checksums/exports.h

19:54:58
-- Installing: /codebuild/output/src122671398/src/github.com/awslabs/install/lib/libaws-checksums.a

19:54:58
-- Installing: /codebuild/output/src122671398/src/github.com/awslabs/install/lib/aws-checksums/cmake/aws-checksums-targets.cmake

19:54:58
-- Installing: /codebuild/output/src122671398/src/github.com/awslabs/install/lib/aws-checksums/cmake/aws-checksums-targets-relwithdebinfo.cmake

19:54:58
-- Installing: /codebuild/output/src122671398/src/github.com/awslabs/install/lib/aws-checksums/cmake/aws-checksums-config.cmake

19:54:58
Test project /codebuild/output/src122671398/src/github.com/awslabs/aws-checksums/build

19:54:58
Start 1: crc32c

19:54:58
1/2 Test #1: crc32c ........................... Passed 0.00 sec

19:54:58
Start 2: crc32

19:54:58
2/2 Test #2: crc32 ............................ Passed 0.00 sec

19:54:58

19:54:58
100% tests passed, 0 tests failed out of 2

19:54:58

19:54:58
Total Test time (real) = 0.00 sec

**Comment by JonathanHenson** [comment]
are you by-chance NOT using CMake?

**Comment by JonathanHenson** [comment]
And if so, maybe this was a debug build? If so I have a simple fix for you.

**Comment by egorpugin** [comment]
I'm fine if you won't fix this.
I use simple patching `s/+[cd]/+g/g`.

(But I'm still curious what flag I need if command line gives that error: `gcc-8 -c file.c -I idir`)

**Comment by JonathanHenson** [comment]
-DDEBUG_BUILD

**Comment by JonathanHenson** [comment]
And I'm all for fixing it, I'm just reluctant to apply a patch when I can't reproduce the error, so I want to find a way to repro it, so I can verify it's fixed.

**Comment by JonathanHenson** [comment]
only use -DDEBUG_BUILD if you in-fact want a debug binary, because it causes GCC builds to fallback to a software implementation which is orders of magnitude slower than the hw accelerated variant.

**Comment by egorpugin** [comment]
No error.

**Comment by JonathanHenson** [comment]
cool, so I'll take your changes and see if we get Debug builds back, which would be awesome.

**Comment by JonathanHenson** [comment]
GCC picks the wrong registers, which is why they're hardcoded. It's safer to just not hit this code path in gcc debug builds, than it is to risk letting gcc pick the wrong ones.
